apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: # local volume - абстракция которая разрешает подам kubernetes обращаться к каталогу который находится на узле кластера
    path: /mnt
  nodeAffinity: # на каком именно узле находится local volume
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube.kopranych.com