apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: local-test
  template:
    metadata:
      labels:
        app: local-test
    spec:
      containers:
        - image: nginx:1.12
          name: nginx
          ports:
            - containerPort: 80
